### ISSUE TITLE
Print History - Shows no history and dates in 1969

### ISSUE THREAD

**Issue by jaymcd** [mkevenaar/FarmPi#10] opened 2021-07-26 16:18 UTC
My print history in the dashboard and history pages does not display any history and shows dates of 1969 ( almost like the db is defaulting to a 
![printhistory](https://user-images.githubusercontent.com/60623834/127023530-a6ba8cae-71ca-42a3-9250-17631a553fa1.PNG)
old Unix date :) )

**Comment by davidzwa** [comment] 2021-07-26 17:05
Dear @jaymcd unfortunately this repository is not the right place for OctoFarm bug reports. Please go check out the following existing issue there
https://github.com/OctoFarm/OctoFarm/issues/618

**Comment by davidzwa** [comment] 2021-07-26 17:05
@mkevenaar feel free to close this as a non-FarmPi issue

**Comment by mkevenaar** [comment] 2021-07-26 18:14
@davidzwa the issue is now closed and marked as Invalid. Thanks for replying!

**Closed** 2021-07-26 18:14 UTC
Labels: Invalid
